- README.md
- monitoring/configuration/grafana.ini
This PR is to make sure the next dialog is always shown when the user signs in the first time:
> grafana.ini: making sure the credentials window appears & update README.md

- ADVANCED.md
- README.md
- docker-compose.yml
Description:
* Integrate waku-frontend, that allows to interact with the node and network
* Navigate to http://localhost:4000/
* Move more technical docs into ADVANCED.md
> Integrate waku-frontend

- docker-compose.yml
- register_rln.sh
Updating nwaku images to release v0.21.3
> updating images to v0.21.3

- monitoring/configuration/dashboards/nwaku-monitoring.json
Add invalid RLN messages to dashboard
> Add invalid RLN messages to dashboard

- docker-compose.yml
- run_node.sh
> fix: using new pubsub-topic flag and updating version to v0.22.0-rc.0

- docker-compose.yml
Bumps nwaku version in docker-compose.yml to 0.23.0.
> bump nwaku version

- docker-compose.yml
Updating default nwaku image to release 0.24.0
> chore: updating image to release 0.24.0

- .env.example
Noticed based on queries in discord, it would be useful to add comments in .env.example file which would help users understand meaning of each of the config.
> chore:add comments for env example to make it more user friendly

- monitoring/configuration/dashboards/nwaku-monitoring.json
- monitoring/configuration/pg-exporter-queries.yml
> Add Postgres Dashboards using Prometheus source

- docker-compose.yml
Updating nwaku version to v0.27.0
> chore: updating nwaku version to 0.27.0

- chkhealth.sh
Just OCD stuff hahah, small fixes on comments only.
> Minor comment typos

- docker-compose.yml
Updating nwaku version to v0.28.0
> chore: updating nwaku version to 0.28.0

- README.md
- docker-compose.yml
- run_node.sh
Integrating [waku-frontend](https://github.com/waku-org/waku-frontend ) into `nwaku-compose`
> Integrating waku frontend

- README.md
- docker-compose.yml
* Update frontend version, pointing to a specific one instead of `latest`. For determinism.
* Change waku frontend port to `4000`.
> Update frontend and port

- docker-compose.yml
Updating nwaku version to v0.30.2
> chore: updating nwaku to v0.30.2

- README.md
This PR follows the next recommendation: https://github.com/waku-org/nwaku-compose/pull/108/files#r1694530485
Thanks for it fryorcraken!
> README.md: better discord invite link

- README.md
Add instructions for updating nodes running in v0.29 or older
> extend upgrade instructions

- run_node.sh
Some VPS have pre-assigned domain names that can be used for WSS.
Attempt to retrieve such domain name if $DOMAIN is not set.
This enables more nodes to support incoming js-waku connections out of the box.
> feat: automatically fetch domain name if possible

- run_node.sh
Also removes `sh: argument expected` error.
> fix: when guessing domain, double check domain returns right ip

- run_node.sh
Done in nwaku 0.32.0 with #2975
> chore: remove install of bind-tools

- docker-compose.yml
- register_rln.sh
> chore: updating image to release v0.33.1

- docker-compose.yml
Correcting a mistake from the previous PR by reverting the changes. Apologies for the oversight!
> chore: update nwaku image

- docker-compose.yml
- register_rln.sh
With release v0.34.0 is ready and image created this is an update to latest official release to be used with nwaku-compose.
> Update nwaku image to latest - v0.34.0

- decrypt_keystore/README.md
- decrypt_keystore/decrypt.py
This PR adds a simple Python script to decrypt the encrypted keystore into the credentials JSON. Helpful for debugging
> feat: keystore decrypt tool

- setup_wizard.sh
thanks for suggestion @fryorcraken
> chore: sepolia to linea sepolia

- README.md
add instructions to gracefully shut down nwaku node in README
> add shut down instructions
