waku-org/nwaku-compose

- README.md
- docker-compose.yml
- run_node.sh
This PR adds a few features to the nwaku-compose, which, I believe, makes it a bit more "production ready"
1. Enabling WSS by defining `DOMAIN` environment variable - it uses Let's Encrypt to obtain SSL certificates and stores them in a volume to make sure you don't hit the LE rate limits
2. You can define `NODEKEY` variable which then uses the value as a `--nodekey` option
3. You can define `EXTRA_ARGS` variable to override or add options in `run_node.sh`
Additional changes in the compose file:
* Update to latest nwaku image
* Openning ports 80 and 8000 for Let's Encrypt challenge and WSS
* Tweaking the env var anchor for extendability
* Making the compose work with podman-compose (adding missing Z options and changing the format of healthcheck command)
> feat: add support for WSS, nodekey and extra args

- run_node.sh
Enrtrees were regenerated. Need to update the old one.
DNS discoverty should continue to work.
> update wakuv2 fleet DNS discovery enrtree

- docker-compose.yml
This is needed to avoid unwanted automatic version upgrades by just using the "latest" image: `postgres:alpine3.18`.
> docker-compose.yml: hard-code PG version to 15.4

- README.md
- docker-compose.yml
Set a maximum amount of 5 retries after container failure, to avoid case of infinitely restarting services in case of configuration failure.
Added section to README.md instructing users how to monitor logs, taking into account that when running on detached mode users are not notified if a container fails during runtime.
closes [#2064](https://github.com/waku-org/nwaku/issues/2064)
> Chore handle docker compose failures

- docker-compose.yml
I believe I raised this in the inital postgres PR, but it sliped in without the volume:)
Not using volume has a few issues:
* every new container creation will result in empty DB (i.e. bad for Store?)
* since the PG is stored **inside** of the container, unless it is cleaned, it may polute the server/machine file system
* it'll be easier to control how much data is taken by PG than relying on the container overlay filesystem (you can easily attach additional storage and point to that rather than using rootfs of the machine)
> fix: use volume for PG data

- README.md
The example command `docker-compose logs <service> -f` works on my local machine and added it to the readme based on that behavior.
However, when using a different machine I got an error, probably due to a different docker-compose version.
Updating the command to `docker-compose logs -f <service>` which is the correct syntax by the documentation.
> fix: correcting readme logs flag

- register_rln.sh
Using full keystore path to avoid the following error encountered on WSL2 Ubuntu on Windows
> fix: using full path for RLN keystore

- .env.example
- .gitignore
- README.md
- docker-compose.yml
- register_rln.sh
- run_node.sh
This PR adds support for `.env` for registration and running docker-compose
It also removes the PG port exposure (let me know if I should submit it as a separate PR)
It also tweaks the shell scripts a bit, but there should be no change in behaviour
> feat: add support for .env

- monitoring/configuration/dashboards/nwaku-monitoring.json
Adding some postgres related panels using Prometheus source.
I will add panels with PostgreSQL source in follow-up PR.
> Add row count and database size panels

- docker-compose.yml
This is to avoid the following error:
```
Error response from daemon: failed to create task for container: failed to create shim task: 
OCI runtime create failed: runc create failed: unable to start container process: error during 
container init: error mounting "/home/petty/nwaku-compose/keystore/keystore.json" to 
rootfs at "/keystore/keystore.json": 
mount /home/petty/nwaku-compose/keystore/keystore.json:/keystore/keystore.json
(via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you 
trying to mount a directory onto a file 
(or vice-versa)? Check if the specified host path exists and is the expected type
```
> docker-compose.yml: keystore.json file should be mounted like a file

- README.md
This PR aims to avoid the following error when using one command from the README.md:
`Invalid content body, could not decode. Unable to deserialize data%`
> Update README.md $(date +%s%N) -> '$(date +%s%N)'

- monitoring/configuration/dashboards/nwaku-monitoring.json
- monitoring/configuration/pg-exporter-queries.yml
In this PR we are showing the number of messages per shard.
The original query (monitoring/configuration/pg-exporter-queries.yml) was designed by @fryorcraken
As a result, we add a panel with the following shape:
> nwaku-monitor/pg-exporter-queries: add new panel to show num msgs per shard

- docker-compose.yml
Mounting the whole `/keystore` directory in `docker-compose.yml` instead of `/keystore/keystore.json`
In case the keystore hasn't been generated yet, the `/keystore` directory will be automatically created by docker instead of a `/keystore/keystore.json` directory.
In general, it's better for the volumes mounted to be intended directories instead of files. 
Advances https://github.com/waku-org/nwaku-compose/issues/32
> mounting keystore directory instead of keystore.json

- register_rln.sh
It was found on sandbox machine that creating the keystore dir ahead of docker run can cause permission issue writing in it. 
Docker run will create the missing directory by its own when mounting it.
I made several tries.
On sandbox machine it is only working when no keystore directory exists before docker run of wakunode.
On my local machine it works both ways.
> fix: removed mkdir keystore before rln registration run

- docker-compose.yml
The postgres container, within the docker-compose file, starts an internal healthcheck. In this commit we are avoiding the following message to appear:
> FATAL:  role "root" does not exist
> docker-compose.yml: pass user and database name when calling pg_isready

- .env.example
Remove the previous hint because a user got confused as he/she thought the `012345` should be kept somehow
> Update .env.example: use ETH_TESTNET_KEY=<YOUR_PRIVATE_KEY_HERE>

- .env.example
- ADVANCED.md
Updates the documentation, companion PR: https://github.com/waku-org/nwaku/pull/2442
> chore(rln-relay): update docs and .env.example to include http instead of ws rpc url

- .env.example
While interacting with a user, I noticed that he set the `ETH_TESTNET_KEY` with a value starting by `0x`. This is expected to be working. Nevertheless, we managed to make it work when he registered using a key without the `0x` prefix.
I'm also giving an example for `ETH_CLIENT_ADDRESS` and therefore keep similar structure in the whole `.env.example` file.
> chore: .env.example: give env vars examples for better understanding the expected format

- README.md
In the README's example, better to not manually pass the timestamp.
It's better practice to let the node set the timestamp, and at the same time, the substitution `'$(date +%s%N)'` keeps creating issues in some machines.
> chore: not passing timestamp in post example

- docker-compose.yml
This is aimed to simplify the assistance we give to users that need to run the Waku node from a cloud server
> leave port 3000 accessible from everywhere by default

- monitoring/configuration/dashboards/nwaku-monitoring.json
We've been recently having issues with two postgres panels. See #73
That information, the db size and the number of rows, is already available in other panels.
Therefore, just removing the 2 panels with errors, as we already have that info available.
Closes #73
> removing db size and num rows broken panels

- chkhealth.sh
Copied and enhanced the script chkhealth.sh added to nwaku.
It supposed to easy the way one can check node health state... hope to lower our node-help channel requests...
> chore: add convenient script for checking node state via /health endpoint

- ADVANCED.md
- docker-compose.yml
Added a new service to regular compose:
pgadmin: will help administer composed postgres DB from a regular browser.
if starting up as: 
```docker compose --profile dbadmin up -d```
_Note: pgadmin image starts only with dbadmin profile, otherwise will not._
User can navigate to http://localhost:15432 and can access admin interface to the composed DB. Credentials are embedded into the docker-compose descriptor.
> chore: pgadmin addon to administer docker store DB

- docker-compose.yml
Quick workaround of docker compose version compatibility issue just appeared with added pgadmin.
> Comment pgadmin support to enable older version of docker-compose to run

- docker-compose.yml
Simple PR to avoid clashes with local running services.
We encounter some node operators facing this issue.
> avoid exposing port 9090 to prevent clashes with other local services

- docker-compose.yml
- register_rln.sh
> Set rln message limit to 100

- run_node.sh
With the new feature of automatically fetching a domain, a user encountered the following issue:
To prevent it, made a small fix in `run_node.sh` not exiting if the certificate couldn't be generated.
I was able to reproduce it locally with the new fix without halting execution:
> fix: don't exit if certificate is not generated

- docker-compose.yml
This is aimed to increase the shared memory allowed to _Postgres_.
Notice that Docker by default limits the shared memory to 64MB which might not be enough for _Postgres_.
With this, we want to prevent issues like:
```nim
postgres-1  | 2024-08-21 13:44:21.948 UTC [28] STATEMENT:  SELECT
postgres-1  |       COUNT(ID)
postgres-1  |     FROM messages
postgres-1  |
postgres-1  | 2024-08-21 13:44:36.540 UTC [28] ERROR:  out of shared memory
postgres-1  | 2024-08-21 13:44:36.540 UTC [28] HINT:  You might need to increase max_locks_per_transaction.
postgres-1  | 2024-08-21 13:44:36.540 UTC [28] STATEMENT:  SELECT
postgres-1  |       COUNT(ID)
postgres-1  |     FROM messages
postgres-1  |
postgres-1  | 2024-08-21 13:44:36.796 UTC [28] ERROR:  out of shared memory
postgres-1  | 2024-08-21 …
```
> docker-compose increase pg shared memory to 1 gb

- monitoring/configuration/dashboards/nwaku-monitoring.json
Changes related to issue: 
- https://github.com/waku-org/nwaku/issues/1945
and nwaku PRs: 
- https://github.com/waku-org/nwaku/pull/2851
- https://github.com/waku-org/nwaku/pull/2920
Changes:
metric panels added:
- in : gross/net
- out: net
> feat: nwaku dashboard with relay per shard, non-relay request rates and traffic panels

- monitoring/configuration/dashboards/nwaku-monitoring.json
while monitoring my own node i realized some minor changes that would not confuse users(showing items in red when it is not an issue) while looking at their dashboard.  
- change data rates to show in bps which is a more common nomeneclature
- remove red threshold for discv5 seen nodes 
- change threshold for connected peers to be 250 as the default config for max connections is 300 peers.
> chore: few intuitive changes in dashboard

- docker-compose.yml
- monitoring/configuration/dashboards/nwaku-monitoring.json
This PR is just an update to the dashboard for this PR https://github.com/waku-org/nwaku/pull/3181 and this issue https://github.com/waku-org/nwaku/issues/3024.
Added two panels:
1. Total Generated Proofs Since Node Start - This value only increases over time.
2. Remaining Proofs Per Epoch - Displays how many proofs can still be generated until the next epoch; it resets with each new epoch.
> chore: grafana panel for remaining proof per epoch

- docker-compose.yml
Add size-based log rotation to effectively manage disk space. As discussed, time-based log rotation is not necessary, as this configuration should adequately address our disk space concerns. 
close #143
> fix: automatic log rotation with size limits

- README.md
- docker-compose.yml
- set_postgres_shm.sh
- set_storage_retention.sh
- setup_wizard.sh
Set a higher SHM if there's 4GB+ of RAM on the host.
Attempting to fix DRIVER_ERROR encountered in the wild.
> feat: dynamically set shm

- docker-compose.yml
- register_rln.sh
This PR is to update the two uses of the RLN contract address to use the address of the newly deployed contract (which is still the same version and functionality as the current contract) as well as update the nwaku docker image version for the one with the fix that also uses the new contract address.
This is to mitigate the spamming issues at the current contract address.
TWN will shortly move to a new contract with membership fees.
> chore: Update sepolia rln contract address

- README.md
- register_rln.sh
As discussed, rln.waku.org isn’t in good shape to be included in the README at the moment. So I’ve temporarily removed that flow from the README.
I’ve also integrated the minting and approval commands directly into register_rln.sh.
@stubbsta — if you’d prefer to give users more control over these commands or advocate for a different approach, I’m happy to revert this change.
> fix: New flow 

- register_rln.sh
- setup_wizard.sh
Fixed the setup_wizard flow minting/approving twice. It now does a single balance check and runs mint/approve only once—saving gas and time.
Per @fryorcraken’s suggestion, the script is now bash-first: switched the shebang to ```#!/usr/bin/env bash ```, keeping the existing bash-isms. If we ever need strict POSIX /bin/sh support, we can refactor later.
> fix: Improve setup wizard 

- .env.example
- .env.example.rln
- README.md
- docker-compose.yml
- run_node.sh
This is a simplification to allow nodes to be run while we have run out of memberships on the new RLN contract.
Changes:
- `run_nwaku.sh`: disable `light-push` and allow RLN_RELAY_CRED_PATH and RLN_RELAY_CRED_PASSWORD to be empty
- `.env.example`: comment out the RLN_RELAY_CRED_PASSWORD and add note about new membership registration being WIP
- `README`: remove rln registration step from option 1 and explain that new membership registration is WIP
> Update default config for relay without publishing

- .gitignore
- FAQ.md
- README.md
- docker-compose.yml
- run_node.sh
After post-sync, rln_tree is no longer needed, so it’s being deprecated.
> chore: rln_tree deprecation

- dogfooding/.env.example.publisher
- dogfooding/dogfood_readme.md
This PR adds dogfooding information for the updated TST contract.
The dogfood_readme.md provides the command to mint tokens by burning ETH for accounts that are not whitelisted.
> Add info for dogfooding to mint tokens with burning ETH method
